<?php

/**
 * @file
 * Provides printer friendly content entities.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\entity\Entity\EntityDisplay;

/**
 * Implements hook_permission().
 */
function APItest_permission() {
  return array(
    'view printer friendly versions' => array(
      'title' => t('View Printer Friendly Versions'),
    ),
    'administer APItest' => array(
      'title' => t('Administer APItest'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function APItest_menu() {
  $items = array();

  $items['admin/config/user-interface/APItest'] = array(
    'title' => 'APItest Configuration',
    'route_name' => 'APItest.configure',
  );

  $items['admin/config/user-interface/APItest/%'] = array(
    'title' => 'APItest Format Configuration',
    'route_name' => 'APItest.format_configure',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function APItest_theme() {
  return array(
    'APItest' => array(
      'template' => 'APItest',
      'pattern' => 'APItest__',
      'variables' => array(
        'header' => NULL,
        'content' => NULL,
        'footer' => NULL,
      ),
      'path' => drupal_get_path('module', 'APItest') . '/theme',
    ),
    'APItest_header' => array(
      'template' => 'APItest-header',
      'pattern' => 'APItest_header__',
      'variables' => array(),
      'path' => drupal_get_path('module', 'APItest') . '/theme',
    ),
    'APItest_footer' => array(
      'template' => 'APItest-footer',
      'pattern' => 'APItest_footer__',
      'variables' => array(),
      'path' => drupal_get_path('module', 'APItest') . '/theme',
    ),
  );
}

/**
 * Implements hook_entity_view_mode_alter().
 */
function APItest_entity_view_mode_info_alter(&$view_modes) {
  $APItest_manager = \Drupal::service('APItest.entity_manager');
  foreach($APItest_manager->getAPItestEntities() as $entity_type => $entity_definition) {
    // Add an additional view mode to this entity.
    $view_modes[$entity_type]['APItest'] = array(
      'label' => t('APItest'),
      'custom_settings' => FALSE,
      'cache' => TRUE,
    );
  }
}

/**
 * Implements hook_entity_view().
 */
function APItest_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode, $langcode) {
  // Load the APItest manager and check if a APItest is available for this
  // entity.
  $APItest_manager = \Drupal::service('APItest.entity_manager');
  $link_builder = \Drupal::service('APItest.link_builder');
  if ($APItest_manager->isAPItestEntity($entity)) {
    // Add the built links to the entity being rendered.
    $entity->content['links']['APItest'] = array(
      '#theme' => 'links__entity__APItest',
      '#links' => $link_builder->buildLinks($entity),
    );
  }
}

