# Schema for the configuration files of the Hardcopy module.

APItest.settings:
  type: mapping
  label: 'Hardcopy settings'
  mapping:
    APItest_entities:
      type: sequence
      label: 'Hardcopy Enabled Entities'
      sequence:
        - type: string
          label: 'Entity'
    open_target_blank:
      type: boolean
      label: 'Open in New Tab'
    css_include:
      type: string
      label: 'CSS Include'
    extract_links:
      type: string
      label: 'Extract Links'
